echo "Kernel 1"
./build/runner 1 1
echo "Kernel 2"
./build/runner 2 1
echo "Kernel 3"
./build/runner 3 1
echo "Kernel 4"
./build/runner 4 1
echo "Kernel 5"
./build/runner 5 1
echo "Kernel 6"
./build/runner 6 1